<?php
echo '
        <div class="jumbotron">
<h1>Why radio-meltdown.ch?</h1>
<p>Die Welt steht bekanntlich vor dem Kollaps. Doch was sind die Gründe? Die Auswahl ist gross: Globale Erwärmung, Atomkrieg, Bankenkrise oder natürlich der Alien-Angriff - der Feind scheint allgegenwärtig, das Bestehen der Menschheit terminiert. Diese Visionen sind alle Folge einer enormen, grösstenteils individuell ausgeschmückten Informationswelle, welche über uns hereinbricht und uns täglich überflutet. Viel schlimmer noch, die Wurzel der meisten Probleme geht in dieser Flut mit unter.</p>
<p><strong>radio-meltdown.ch</strong> widmet sich dem bedrohlichsten aller Probleme: Dem Zerfall der Priorität von Kunst und Kultur, welcher zwangsläufig die globale Verblödung oder auch den „Intellectual Meltdown“ herbeiführt. Herangezogen wird so eine Generation von gleichgültigen Ja-Sagern, die nur noch auf inhaltsleere Parolen und Worthülsen anspringen. Wer sich die populären Medien wie 20min, Blick, RTL, VIVA oder MTV mal ansieht, muss miterleben, wie der Inhalt auch hier immer mehr verschwindet. Als Folge dessen beginnt der Rezipient die Medien zu konsumieren, anstatt sie zu hinterfragen und mit ihr einen Diskurs einzugehen. Dieses Verhalten überträgt sich nun auf die Kunst, mit wesentlich schlimmeren Folgen. Im Gegensatz zu den Medien, welche immer noch hauptsächlich den Auftrag haben zu informieren, steht in der Kunst vielmehr der Diskurs im Vordergrund. Wer auf ihn verzichtet, ist nicht mehr in der Lage, Kunst zu verstehen. Daraus entstand zwangsläufig die moderne Pop-Musik. Sie gipfelt nun in Vertretern wie David Guetta, Pitbull oder den Black Eyed Peas. Die Medien haben neben ihrem eigenen Inhalt auch die Aussagekraft der Pop-Musik mitgeopfert. Die Kunst wird nicht weiter beachtet, die Medien haben eine Übermacht in der Meinungsbildung, die individuelle Meinungsbildung schwindet langsam aber sicher dahin. Vorurteile, Neid, Angst, Intoleranz oder gar Rassismus haben die Möglichkeit, in grosser Vielfalt zu gedeihen.</p>
<p>Too much? Keineswegs! <strong>radio-meltdown.ch</strong> übertreibt so oft und wo immer es auch will. Unser Programm setzt sich neben dem musikalischen vor allem aus humorvollem, satirischem Inhalt zusammen. Detailkonzept folgt.</p>
        </div>
    ';
?>